import { prisma } from "@/lib/db";
import { Prisma } from "@/generated/prisma";
import { transitionQuotation } from "./quotation";
import { writeAudit } from "@/lib/audit";

export async function convertQuoteToOrder(quotationId: string, actorId: string) {
  const quotation = await prisma.quotation.findUnique({
    where: { id: quotationId },
    include: { lines: { include: { product: true } } },
  });

  if (!quotation) throw new Error("Quotation not found");
  if (quotation.status !== "APPROVED") throw new Error("Only APPROVED quotations can be confirmed");

  // Generate order number O-YYYYMMDD-XXXX
  const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const randomStr = Math.floor(1000 + Math.random() * 9000).toString();
  const orderNumber = `O-${dateStr}-${randomStr}`;

  let newOrder;

  // Transaction to ensure atomicity
  await prisma.$transaction(async (tx) => {
    // 1. Create the Order
    newOrder = await tx.order.create({
      data: {
        orderNumber,
        quotationId: quotation.id,
        customerId: quotation.customerId,
        status: "CONFIRMED",
        subtotal: quotation.subtotal,
        taxAmount: quotation.taxAmount,
        totalAmount: quotation.totalAmount,
        currency: quotation.currency,
      },
    });

    // 2. Create the OrderLines
    const orderLinesData = quotation.lines.map((line) => ({
      orderId: newOrder!.id,
      productId: line.productId,
      quantity: line.quantity,
      unitPrice: line.unitPrice,
      taxAmount: line.taxAmount, 
      totalAmount: line.lineTotal,
      productType: line.product.productType,
      // Note: subscriptionPlanId would be matched/generated by Person 3 later
      // We pass null for now as per the spec, "resolved by Person 3"
    }));

    await tx.orderLine.createMany({
      data: orderLinesData,
    });
  });

  // 3. Transition Quote to CONFIRMED
  await transitionQuotation(quotationId, "CONFIRM", actorId);

  await writeAudit({
    entityType: "Order",
    entityId: newOrder!.id,
    action: "CREATED",
    actorId,
    after: newOrder,
  });

  return newOrder;
}
